### ISSUE TITLE
Issues downloading seegSDM

### ISSUE THREAD

**Issue by labade** [SEEG-Oxford/seegSDM#41]
Hello there,

I am trying to install the seegSDM package but I am getting the following error:

> devtools::install_github('SEEG-Oxford/seegSDM')
Downloading github repo SEEG-Oxford/seegSDM@master
Error in stri_detect_regex(string, pattern, opts_regex = attr(pattern,  : 
  object 'C_stri_detect_regex' not found

Is the package still available for downloading? If so, could this be an installation bug? 

Thanks very much for your assistance. 

# Mac OS X Yosemite 10.10.5

**Comment by goldingn** [comment]
Hi,

Looks like your error is in `devtools`, not `seegSDM`. Apparently it's failing trying to download the package source. I'm running Yosemite 10.10.5 too and can't replicate this error, it installs fine for me (see below).

`C_stri_detect_regex`is from the `stringi` package: https://github.com/Rexamine/stringi/blob/master/src/stri_stringi.cpp
As far as I can tell (e.g. here) `stringi` is not a dependency of  `devtools` (nor is it a dependency of `seegSDM`), but it may have been a `devtools` dependency in the past, which suggests your `devtools` installation might be out of date?

You can check by doing:
```r
installed.packages()['devtools', 'Version']
```

I get:
```
[1] "1.9.1"
```
which is the latest version on CRAN. If it's an earlier version, you can update `devtools` with:
```r
install.packages('devtools')
```

----

For reference, when I run this:
```r
devtools::install_github('SEEG-Oxford/seegSDM')
```
I get:
```
Downloading GitHub repo SEEG-Oxford/seegSDM@master
Installing seegSDM
Skipping 3 packages ahead of CRAN: raster, rgdal, sp
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/3_/svr6htc10z16mbss9gn6p2n80000gq/T/RtmpLydU43/devtools14bb76d4e8e8/SEEG-Oxford-seegSDM-b2f2628'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

* installing *source* package ‘seegSDM’ ...
** R
** data
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (seegSDM)
```

**Comment by labade** [comment]
Hello there goldingn, it seems that the problem was indeed with my (old) version of R. For some reason it wasn't able to install the packages. After a quick reinstallation the package is now working smoothly. Thanks very much for your help.

Cheers,

Leandro

**Comment by goldingn** [comment]
Great, glad this is working now!
